const test=require('node:test');const assert=require('node:assert/strict');const {TECHNICAL_TEST_TITLE,isTechnicalTest,visibleRows,displayedRank}=require('./contentPresentation');
test('technical playback content is classified and excluded from ordinary backend rows',()=>{const testVideo={id:'test',title:TECHNICAL_TEST_TITLE};assert.equal(isTechnicalTest(testVideo),true);assert.deepEqual(visibleRows([{title:'Trending',items:[testVideo,{id:'real',title:'Real'}]}])[0].items.map(x=>x.id),['real'])});
test('empty recommendation rows remain hidden',()=>assert.deepEqual(visibleRows([{title:'Empty',items:[]}]),[]));
test('rank appears only when both row and item provide valid ranking',()=>{assert.equal(displayedRank({displayRanking:true},{rank:1}),1);assert.equal(displayedRank({displayRanking:false},{rank:1}),null);assert.equal(displayedRank({displayRanking:true},{}),null)});
test('consumer navigation does not expose Creator Studio',()=>{const fs=require('node:fs');const navigation=fs.readFileSync('src/components/Header.js','utf8')+fs.readFileSync('src/components/MobileNavigation.js','utf8');assert.doesNotMatch(navigation,/Creator Studio/i)});
test('hero is cinematic, semantic, reduced-motion aware, and excludes the technical sample',()=>{const fs=require('node:fs');const hero=fs.readFileSync('src/components/HeroBanner.js','utf8');assert.match(hero,/height:'84vh'/);assert.match(hero,/accessibilityLabel={`Play/);assert.match(hero,/prefers-reduced-motion/);assert.doesNotMatch(hero,/Player Test — Cloudinary Sample/)});
test('home keeps live rows first and restores labelled editorial concepts only when rows are empty',()=>{const fs=require('node:fs');const home=fs.readFileSync('src/screens/HomeScreen.js','utf8');assert.match(home,/homeScreenContent\(state, editorialRows, editorialTitles\)/);assert.match(home,/non-playable Ripple editorial concepts/);assert.match(home,/Technical Playback Test/)});
test('coming soon hero concepts offer More Info and Notify Me without Play',()=>{const fs=require('node:fs');const hero=fs.readFileSync('src/components/HeroBanner.js','utf8');assert.match(hero,/!playable\?<Pressable/);assert.match(hero,/Notify Me/);assert.match(hero,/More Info/)});
test('title detail routes load their canonical backend resource',()=>{const fs=require('node:fs');const shell=fs.readFileSync('src/navigation/AppShell.js','utf8');assert.match(shell,/titleIdFromPath/);assert.match(shell,/api\(`\/api\/content\/\$\{encodeURIComponent\(id\)\}`\)/)});
test('details and primary navigation use semantic controls',()=>{const fs=require('node:fs');const details=fs.readFileSync('src/components/ContentDetails.js','utf8');const header=fs.readFileSync('src/components/Header.js','utf8');assert.match(details,/accessibilityLabel="Close details"/);assert.match(details,/accessibilityLabel={`Play/);assert.match(header,/accessibilityRole="navigation"/);assert.match(header,/accessibilityRole="link"/)});
test('home row ordering prioritises major OTT discovery rails',()=>{const {orderHomeRows}=require('./contentPresentation');const rows=orderHomeRows([{title:'Coming Soon',items:[{id:'c'}]},{title:'Trending Now',items:[{id:'t'}]},{title:'Continue Watching',items:[{id:'w'}]}]);assert.deepEqual(rows.map(x=>x.title),['Continue Watching','Trending Now','Coming Soon'])});
test('home renders editorial fallback for the real empty API response shape',()=>{
  const {homeScreenContent}=require('./contentPresentation');
  const response={rows:[{id:'featured',items:[]},{id:'popularThisWeek',items:[]},{id:'newReleases',items:[]}],featured:[],trending:[],newest:[],continueWatching:[]};
  const editorial=[{id:'coming-soon',items:[{id:'preview'}]}];
  const result=homeScreenContent({...response,hero:null},editorial,[{id:'preview'}]);
  assert.equal(result.showEditorial,true);
  assert.deepEqual(result.live,[]);
  assert.deepEqual(result.featured.map(item=>item.id),['preview']);
  assert.deepEqual(result.concepts.map(row=>row.id),['coming-soon']);
});
test('home removes nullish and unidentified content before merging and deduplicating',()=>{
  const {homeScreenContent}=require('./contentPresentation');
  const validContent={id:'valid',title:'Valid'};
  const result=homeScreenContent({rows:[null,{id:'featured',items:[null,undefined,validContent]}],hero:null},[],[]);
  assert.equal(result.showEditorial,false);
  assert.deepEqual(result.live[0].items,[validContent]);
  assert.deepEqual(result.featured,[validContent]);
});
test('editorial catalogue centralises 29 approved Cloudinary assets and rejects the retired portrait',()=>{const fs=require('node:fs');const catalogue=fs.readFileSync('src/data/editorial.js','utf8');assert.equal((catalogue.match(/IMG_\d+\.png/g)||[]).length,29);assert.doesNotMatch(catalogue,/IMG_1070/);for(const field of ['heroImageUrl','landscapeImageUrl','portraitImageUrl','releaseStatus','editorialStatus','playable'])assert.match(catalogue,new RegExp(field));});
test('editorial artwork uses responsive Cloudinary delivery and distinct card aspect ratios',()=>{const fs=require('node:fs');const helper=fs.readFileSync('src/utils/cloudinary.js','utf8');const cards=fs.readFileSync('src/components/ContentCard.js','utf8');assert.match(helper,/f_auto,q_auto,c_fill/);assert.match(cards,/aspectRatio:16\/9/);assert.match(cards,/aspectRatio:2\/3/);});
