const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const read=p=>fs.readFileSync(p,'utf8');
test('catalogue sizing follows the requested phone tablet desktop and wide formulas',()=>{const c=read('src/components/ContentCard.js');for(const formula of [/width\*\.84,340/,/Math\.max\(300,width\*\.43\)/,/Math\.max\(320,width\*\.27\)/,/Math\.max\(360,width\*\.23\)/,/width\*\.45,185/,/Math\.max\(190,width\*\.27\)/,/Math\.max\(210,width\*\.17\)/])assert.match(c,formula);assert.match(c,/aspectRatio:16\/9/);assert.match(c,/aspectRatio:2\/3/);assert.match(c,/scrollSnapAlign:'start'/)});
test('rails use shared responsive rhythm, aligned title-only headers, snapping, and overflow-aware controls',()=>{const r=read('src/components/ContentRail.js'),t=read('src/theme/tokens.js');assert.match(r,/horizontal/);assert.doesNotMatch(r,/row\.reason/);assert.match(r,/tokens\.rail\.headingGap/);assert.match(r,/tokens\.rail\.sectionGap/);assert.match(t,/sectionGap: \{ mobile:24, tablet:28, desktop:32 \}/);assert.match(t,/headingGap: \{ mobile:16, tablet:18, desktop:20 \}/);assert.match(t,/featuredGap: \{ mobile:30, tablet:34, desktop:40 \}/);assert.match(r,/scrollSnapType: 'x proximity'/);assert.match(r,/overscrollBehaviorInline: 'contain'/);assert.match(r,/width >= 1024 && !isTouchDevice\(\) && hasOverflow/);assert.match(r,/accessibilityState=\{\{ disabled: atStart \}\}/)});
test('mobile navigation exposes five app destinations with safe-area and accessible tabs',()=>{const n=read('src/components/MobileNavigation.js');for(const x of ['Home','New','Search','My List','Profile'])assert.match(n,new RegExp(x));assert.match(n,/accessibilityRole="tablist"/);assert.match(n,/minWidth:44/);assert.match(n,/safe-area-inset-bottom/);assert.doesNotMatch(n,/[⌂✦●]/)});
test('mobile hero separates artwork and information and removes touch arrows',()=>{const h=read('src/components/HeroBanner.js');assert.match(h,/mobileArtwork:\{height:'55svh',minHeight:430/);assert.match(h,/mobile\?info:null/);assert.match(h,/!mobile&&list.length>1&&!isTouchDevice/);assert.match(h,/PanResponder/);assert.match(h,/12000/);assert.match(h,/prefers-reduced-motion/)});
test('shared gutters, overflow containment, bottom clearance, and safe areas are applied',()=>{const l=read('src/utils/layout.js'),home=read('src/screens/HomeScreen.js'),shell=read('src/navigation/AppShell.js');assert.match(l,/width < 600 \? 16/);assert.match(l,/width < 1024 \? 24/);assert.match(l,/width < 1600 \? 48/);assert.match(home,/overflowX:'hidden'/);assert.match(shell,/overflowX:'hidden'/);assert.match(home,/safe-area-inset-bottom/)});
test('hero data supports desktop tablet and mobile focal positioning',()=>{const data=read('src/data/editorial.js'),hero=read('src/components/HeroBanner.js');for(const key of ['imagePositionDesktop','imagePositionTablet','imagePositionMobile']){assert.match(data,new RegExp(key));assert.match(hero,new RegExp(key))}});
test('mobile details are full screen and playback/details behavior remains wired',()=>{const d=read('src/components/ContentDetails.js'),shell=read('src/navigation/AppShell.js');assert.match(d,/mobileModal:\{maxWidth:'none',maxHeight:'100%',height:'100%'/);assert.match(d,/safe-area-inset-bottom/);assert.match(shell,/onPlay=\{play\}/);assert.match(shell,/ContentDetails/)});
