const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');
const read=p=>fs.readFileSync(p,'utf8');
test('catalogue sizing follows distinct phone tablet and desktop formulas',()=>{const c=read('src/components/ContentCard.js');assert.match(c,/width\*\.82,330/);assert.match(c,/width\*\.42,350/);assert.match(c,/width\*\.24,300/);assert.match(c,/width\*\.44/);assert.match(c,/aspectRatio:16\/9/);assert.match(c,/aspectRatio:2\/3/);assert.match(c,/scrollSnapAlign:'start'/)});
test('rails use a collision-free header and native snapping',()=>{const r=read('src/components/ContentRail.js');assert.match(r,/horizontal/);assert.match(r,/headingCopy:\{gap:7/);assert.match(r,/marginBottom:16/);assert.match(r,/scrollSnapType:'x proximity'/);assert.match(r,/overscrollBehaviorInline:'contain'/);assert.match(r,/!isTouchDevice/)});
test('mobile navigation exposes five app destinations with safe-area and accessible tabs',()=>{const n=read('src/components/MobileNavigation.js');for(const x of ['Home','New','Search','My List','Profile'])assert.match(n,new RegExp(x));assert.match(n,/accessibilityRole="tablist"/);assert.match(n,/minWidth:44/);assert.match(n,/safe-area-inset-bottom/);assert.doesNotMatch(n,/[⌂✦●]/)});
test('mobile hero separates artwork and information and removes touch arrows',()=>{const h=read('src/components/HeroBanner.js');assert.match(h,/mobileArtwork:\{height:'55svh',minHeight:430/);assert.match(h,/mobile\?info:null/);assert.match(h,/!mobile&&list.length>1&&!isTouchDevice/);assert.match(h,/PanResponder/);assert.match(h,/12000/);assert.match(h,/prefers-reduced-motion/)});
test('shared gutters, overflow containment, bottom clearance, and safe areas are applied',()=>{const l=read('src/utils/layout.js'),home=read('src/screens/HomeScreen.js'),shell=read('src/navigation/AppShell.js');assert.match(l,/width < 768 \? 16/);assert.match(l,/width < 1024 \? 24/);assert.match(home,/overflowX:'hidden'/);assert.match(shell,/overflowX:'hidden'/);assert.match(home,/safe-area-inset-bottom/)});
test('hero data supports desktop tablet and mobile focal positioning',()=>{const data=read('src/data/editorial.js'),hero=read('src/components/HeroBanner.js');for(const key of ['imagePositionDesktop','imagePositionTablet','imagePositionMobile']){assert.match(data,new RegExp(key));assert.match(hero,new RegExp(key))}});
test('mobile details are full screen and playback/details behavior remains wired',()=>{const d=read('src/components/ContentDetails.js'),shell=read('src/navigation/AppShell.js');assert.match(d,/mobileModal:\{maxWidth:'none',maxHeight:'100%',height:'100%'/);assert.match(d,/safe-area-inset-bottom/);assert.match(shell,/onPlay=\{play\}/);assert.match(shell,/ContentDetails/)});
