import React, { useCallback, useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { api } from '../services/api';
import { tokens } from '../theme/tokens';

export const BILLING_UNAVAILABLE = 'Subscriptions are not available yet. Continue watching with the Free plan.';
const list = value => Array.isArray(value) ? value : value?.plans || value?.data || [];
const feature = (plan, key, fallback='—') => plan?.features?.[key] ?? plan?.[key] ?? fallback;
export function normalizePlans(value) { return list(value).filter(Boolean); }
export function subscriptionLabel(subscription) {
  if (!subscription) return 'Free';
  if (subscription.cancelAtPeriodEnd) return `${subscription.plan?.name || subscription.planName || 'Plan'} · ends after this billing period`;
  return `${subscription.plan?.name || subscription.planName || 'Plan'} · ${String(subscription.status || 'pending').replace('_',' ')}`;
}
export function PlansScreen({user,subscription,navigate,onSubscription}) {
  const {width}=useWindowDimensions(); const [plans,setPlans]=useState([]),[status,setStatus]=useState('loading'),[message,setMessage]=useState(''),[busy,setBusy]=useState('');
  const load=useCallback(async()=>{setStatus('loading');setMessage('');try{const result=normalizePlans(await api('/api/subscriptions/plans'));setPlans(result);setStatus(result.length?'ready':'empty')}catch(error){setStatus('error');setMessage(error.message||'Plans could not be loaded.')}},[]);
  useEffect(()=>{load()},[load]);
  async function checkout(plan){if(busy)return;if(!user){if(typeof sessionStorage!=='undefined')sessionStorage.setItem('ripple_intended_route','/plans');navigate('/signin');return}setBusy(plan.id||plan.slug);setMessage('Opening secure checkout…');try{const result=await api('/api/subscriptions/checkout',{method:'POST',body:JSON.stringify({planId:plan.id||plan.slug})});const url=result.checkoutUrl||result.url;if(!url)throw Object.assign(new Error(BILLING_UNAVAILABLE),{code:'BILLING_NOT_CONFIGURED'});const parsed=new URL(url);if(!/^https:$/.test(parsed.protocol))throw new Error('The checkout provider returned an invalid address.');if(typeof window!=='undefined')window.location.assign(parsed.href)}catch(error){setMessage(error.code==='BILLING_NOT_CONFIGURED'||/billing|not configured|unavailable/i.test(error.message)?BILLING_UNAVAILABLE:(error.message||'Checkout could not be started.'))}finally{setBusy('')}}
  return <ScrollView contentContainerStyle={s.page}><View style={s.heading}><Text style={s.kicker}>WATCH YOUR WAY</Text><Text accessibilityRole="header" style={s.title}>Choose a Ripple plan</Text><Text style={s.copy}>Browse the free catalogue anytime. Paid checkout happens securely with our billing provider; Ripple never receives your card details.</Text></View><Text accessibilityLiveRegion="polite" style={s.live}>{status==='loading'?'Loading plans…':message}</Text>{status==='error'?<Pressable accessibilityRole="button" onPress={load} style={s.retry}><Text style={s.buttonText}>Try again</Text></Pressable>:null}{status==='empty'?<Text style={s.copy}>No plans are available right now.</Text>:null}<View style={[s.grid,width>=600&&s.gridTablet]}>{plans.map(plan=>{const id=plan.id||plan.slug;const current=Boolean(plan.current)||id===subscription?.planId;return <View key={id||plan.name} style={[s.card,plan.recommended&&s.recommended]}>{plan.recommended?<Text style={s.recommendedText}>RECOMMENDED</Text>:null}<Text style={s.plan}>{plan.name}</Text><Text style={s.price}>{plan.formattedPrice||`${plan.currency||''} ${plan.monthlyPrice??plan.price??''}`}<Text style={s.period}> / month</Text></Text><Text style={s.feature}>Quality · {feature(plan,'videoQuality')}</Text><Text style={s.feature}>Streams · {feature(plan,'simultaneousStreams')}</Text><Text style={s.feature}>Downloads · {String(feature(plan,'downloads'))}</Text><Text style={s.feature}>Advertisements · {String(feature(plan,'advertisements'))}</Text><Pressable accessibilityRole="button" disabled={current||Boolean(busy)} onPress={()=>checkout(plan)} style={[s.button,(current||busy)&&s.disabled]}><Text style={s.buttonText}>{current?'Current plan':busy===id?'Please wait…':String(plan.name).toLowerCase()==='free'?'Continue free':'Choose plan'}</Text></Pressable></View>})}</View>{subscription?<Pressable onPress={()=>navigate('/account/subscription')} style={s.manage}><Text style={s.manageText}>Manage subscription · {subscriptionLabel(subscription)}</Text></Pressable>:null}</ScrollView>;
}
const s=StyleSheet.create({page:{flexGrow:1,backgroundColor:tokens.color.background,paddingHorizontal:'4%',paddingTop:110,paddingBottom:130},heading:{maxWidth:720,alignSelf:'center',alignItems:'center'},kicker:{color:tokens.color.accentSoft,fontWeight:'900',letterSpacing:2},title:{color:tokens.color.text,fontSize:40,fontWeight:'900',textAlign:'center',marginTop:8},copy:{color:tokens.color.muted,lineHeight:22,textAlign:'center',marginTop:10},live:{color:tokens.color.accentSoft,minHeight:42,textAlign:'center',paddingTop:18},grid:{width:'100%',maxWidth:1180,alignSelf:'center',gap:16},gridTablet:{flexDirection:'row',flexWrap:'wrap'},card:{flexGrow:1,flexBasis:250,minWidth:0,padding:24,borderRadius:14,borderWidth:1,borderColor:tokens.color.border,backgroundColor:tokens.color.surface,gap:12},recommended:{borderColor:tokens.color.accentSoft,backgroundColor:'#171425'},recommendedText:{color:tokens.color.accentSoft,fontSize:11,fontWeight:'900',letterSpacing:1.3},plan:{color:tokens.color.text,fontSize:25,fontWeight:'900'},price:{color:tokens.color.text,fontSize:22,fontWeight:'800'},period:{fontSize:13,color:tokens.color.muted},feature:{color:'#d5d1dc'},button:{minHeight:48,marginTop:8,borderRadius:8,backgroundColor:tokens.color.text,alignItems:'center',justifyContent:'center'},buttonText:{color:tokens.color.background,fontWeight:'900'},disabled:{opacity:.55},retry:{alignSelf:'center',minHeight:48,paddingHorizontal:24,justifyContent:'center',backgroundColor:tokens.color.text,borderRadius:8,marginBottom:20},manage:{minHeight:48,alignSelf:'center',justifyContent:'center',marginTop:25},manageText:{color:tokens.color.accentSoft,fontWeight:'800'}});
