import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { api } from '../services/api';
import { signOut } from '../services/auth';
import { tokens } from '../theme/tokens';

const choices={languages:['Hindi','English','Tamil','Telugu','Malayalam'],subtitles:['Off','English','Hindi'],genres:['Mythology and Epics','AI Cinema','Science Fiction','Fantasy','Animation','Regional Stories']};
export function ProfileScreen({route,user,navigate,onLogout,onRefresh}){const create=route==='/profiles/new',onboarding=route==='/onboarding',account=route==='/account';const[name,setName]=useState(''),[country,setCountry]=useState(user?.country||'India'),[language,setLanguage]=useState('Hindi'),[subtitle,setSubtitle]=useState('English'),[genres,setGenres]=useState([]),[kids,setKids]=useState(false),[message,setMessage]=useState('');
 const toggle=g=>setGenres(v=>v.includes(g)?v.filter(x=>x!==g):[...v,g]); async function save(){setMessage('Saving…');try{await api(create?'/api/profiles':'/api/profiles/preferences',{method:create?'POST':'PUT',body:JSON.stringify({name,country,languages:[language],subtitleLanguage:subtitle,genres,kids,maturityPreference:kids?'kids':'standard'})});setMessage('Preferences saved. Refreshing your recommendations…');onRefresh?.();navigate('/');}catch(e){setMessage(e.message||'Preferences could not be saved.')}}
 if(route==='/profiles')return <ScrollView contentContainerStyle={s.page}><Text style={s.kicker}>RIPPLE PROFILES</Text><Text accessibilityRole="header" style={s.title}>Who’s watching?</Text><View style={s.profiles}><Pressable accessibilityRole="button" onPress={()=>navigate('/onboarding')} style={s.avatar}><Text style={s.avatarText}>{(user?.displayName||'Y')[0]}</Text><Text style={s.choice}>{user?.displayName||'You'}</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>navigate('/profiles/new')} style={s.avatar}><Text style={s.plus}>＋</Text><Text style={s.choice}>Add profile</Text></Pressable></View></ScrollView>;
 if(account)return <ScrollView contentContainerStyle={s.page}><View style={s.panel}><Text style={s.kicker}>YOUR RIPPLE</Text><Text accessibilityRole="header" style={s.title}>Account & profiles</Text><Text style={s.copy}>{user?.email||'Sign in to sync My List, progress and preferences.'}</Text><Pressable onPress={()=>navigate(user?'/profiles':'/signin')} style={s.primary}><Text style={s.primaryText}>{user?'Manage profiles':'Sign in'}</Text></Pressable>{user?<><Pressable onPress={()=>navigate('/account/subscription')} style={s.secondary}><Text style={s.choice}>Manage subscription</Text></Pressable><Pressable onPress={async()=>{await signOut();onLogout?.();navigate('/')}} style={s.secondary}><Text style={s.choice}>Sign out</Text></Pressable></>:null}</View></ScrollView>;
 return <ScrollView contentContainerStyle={s.page}><View style={s.panel}><Text style={s.kicker}>{create?'CREATE PROFILE':'PERSONALISE RIPPLE'}</Text><Text accessibilityRole="header" style={s.title}>{create?'Make it yours':'What do you love?'}</Text>{create?<TextInput accessibilityLabel="Profile name" value={name} onChangeText={setName} placeholder="Profile name" placeholderTextColor={tokens.color.muted} style={s.input}/>:null}<TextInput accessibilityLabel="Country" value={country} onChangeText={setCountry} placeholder="Country" placeholderTextColor={tokens.color.muted} style={s.input}/><Choice title="Content language" values={choices.languages} selected={[language]} onPress={setLanguage}/><Choice title="Subtitle preference" values={choices.subtitles} selected={[subtitle]} onPress={setSubtitle}/><Choice title="Choose at least three genres" values={choices.genres} selected={genres} onPress={toggle}/><Pressable accessibilityRole="checkbox" accessibilityState={{checked:kids}} onPress={()=>setKids(!kids)} style={[s.chip,kids&&s.chipOn]}><Text style={s.choice}>{kids?'✓ ':''}Kids profile · family maturity</Text></Pressable>{message?<Text accessibilityRole="status" style={s.copy}>{message}</Text>:null}<Pressable disabled={!country||!language||genres.length<3||(create&&!name)} onPress={save} style={[s.primary,(!country||genres.length<3)&&s.disabled]}><Text style={s.primaryText}>Save and continue</Text></Pressable></View></ScrollView>}
function Choice({title,values,selected,onPress}){return <View><Text style={s.label}>{title}</Text><View style={s.chips}>{values.map(v=><Pressable key={v} accessibilityRole="checkbox" accessibilityState={{checked:selected.includes(v)}} onPress={()=>onPress(v)} style={[s.chip,selected.includes(v)&&s.chipOn]}><Text style={s.choice}>{v}</Text></Pressable>)}</View></View>}
const s=StyleSheet.create({page:{flexGrow:1,backgroundColor:tokens.color.background,alignItems:'center',justifyContent:'center',padding:24},panel:{width:'100%',maxWidth:720,padding:28,borderRadius:20,backgroundColor:tokens.color.surface,borderWidth:1,borderColor:tokens.color.border,gap:16},kicker:{color:tokens.color.accentSoft,fontWeight:'900',letterSpacing:2},title:{color:tokens.color.text,fontSize:36,fontWeight:'900'},copy:{color:tokens.color.muted,lineHeight:22},input:{height:52,borderWidth:1,borderColor:tokens.color.border,borderRadius:10,color:tokens.color.text,paddingHorizontal:14},label:{color:tokens.color.text,fontWeight:'800',marginBottom:8},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{minHeight:44,paddingHorizontal:14,borderRadius:22,borderWidth:1,borderColor:tokens.color.border,alignItems:'center',justifyContent:'center'},chipOn:{borderColor:tokens.color.accentSoft,backgroundColor:'rgba(128,112,232,.25)'},choice:{color:tokens.color.text,fontWeight:'700'},primary:{minHeight:50,backgroundColor:tokens.color.text,borderRadius:9,alignItems:'center',justifyContent:'center'},primaryText:{color:tokens.color.background,fontWeight:'900'},secondary:{minHeight:48,borderWidth:1,borderColor:tokens.color.border,borderRadius:9,alignItems:'center',justifyContent:'center'},disabled:{opacity:.4},profiles:{flexDirection:'row',gap:28,marginTop:30},avatar:{alignItems:'center',gap:10,minWidth:110,minHeight:130},avatarText:{width:96,height:96,borderRadius:18,backgroundColor:tokens.color.accent,overflow:'hidden',color:'#fff',fontSize:54,fontWeight:'900',textAlign:'center',textAlignVertical:'center'},plus:{width:96,height:96,borderRadius:18,borderWidth:2,borderColor:tokens.color.border,color:tokens.color.text,fontSize:44,textAlign:'center',textAlignVertical:'center'}});
