import React, { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { api } from '../services/api';
import { arrayFrom, isTechnicalTest } from '../utils/content';
import { ContentCard } from '../components/ContentCard';
import { StatePanel } from '../components/StatePanel';
import { tokens } from '../theme/tokens';
const suggestions=['Mythology','Fantasy','Animation','Regional stories'];
const readRecent=()=>{try{return JSON.parse(globalThis.localStorage?.getItem('ripple_recent_searches')||'[]').slice(0,6)}catch{return[]}};
export function SearchScreen({onOpen}) { const[q,setQ]=useState(''),[items,setItems]=useState([]),[recent,setRecent]=useState(readRecent),[loading,setLoading]=useState(false),[error,setError]=useState(''),[attempt,setAttempt]=useState(0); const term=q.trim(); useEffect(()=>{if(term.length<2){setItems([]);setError('');setLoading(false);return;}const controller=new AbortController(),timer=setTimeout(async()=>{setLoading(true);setError('');try{const data=await api(`/api/search?q=${encodeURIComponent(term)}`,{signal:controller.signal});setItems(arrayFrom(data,'results').filter(item=>!isTechnicalTest(item)));setRecent(old=>{const next=[term,...old.filter(x=>x.toLowerCase()!==term.toLowerCase())].slice(0,6);try{globalThis.localStorage?.setItem('ripple_recent_searches',JSON.stringify(next))}catch{}return next})}catch(e){if(e.name!=='AbortError'&&e.code!=='ABORTED')setError(typeof navigator!=='undefined'&&!navigator.onLine?'You’re offline. Reconnect to search Ripple.':e.message)}finally{if(!controller.signal.aborted)setLoading(false)}},350);return()=>{clearTimeout(timer);controller.abort()}},[term,attempt]); const prompts=[...recent,...suggestions.filter(x=>!recent.includes(x))]; return <ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" style={s.page} contentContainerStyle={s.content}><Text accessibilityRole="header" style={s.title}>Search</Text><View style={s.searchBox}><Text accessibilityElementsHidden style={s.searchMark}>⌕</Text><TextInput accessibilityLabel="Search Ripple" autoFocus value={q} onChangeText={setQ} returnKeyType="search" placeholder="Titles, creators, genres and languages" placeholderTextColor="#898592" style={s.input}/>{q?<Pressable accessibilityRole="button" accessibilityLabel="Clear search" onPress={()=>setQ('')} style={s.clear}><Text style={s.clearText}>×</Text></Pressable>:null}</View>{loading?<View accessibilityLabel="Loading search results" style={s.skeletonGrid}>{[0,1,2,3].map(i=><View key={i} style={s.skeleton}/>)}</View>:error?<StatePanel title="Search couldn’t load" message={error} action="Try again" onAction={()=>setAttempt(x=>x+1)}/>:term.length<2?<View style={s.explore}><Text style={s.sectionTitle}>{recent.length?'Recent searches':'Explore Ripple'}</Text><View style={s.chips}>{prompts.map(value=><Pressable key={value} onPress={()=>setQ(value)} style={({pressed})=>[s.chip,pressed&&s.pressed]}><Text style={s.chipText}>{value}</Text></Pressable>)}</View></View>:items.length?<View style={s.grid}>{items.map(item=><ContentCard key={item.id||item._id} item={item} portrait onOpen={onOpen}/>)}</View>:<StatePanel title="No results" message="Try a different title, creator, genre, or language."/>}</ScrollView>; }
const s=StyleSheet.create({page:{flex:1,backgroundColor:tokens.color.background},content:{paddingHorizontal:16,paddingTop:76,paddingBottom:'max(110px, calc(84px + env(safe-area-inset-bottom)))',minHeight:'100%'},title:{color:tokens.color.text,fontSize:32,fontWeight:'900',marginVertical:16},searchBox:{minHeight:56,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:tokens.color.border,borderRadius:16,backgroundColor:tokens.color.surface},searchMark:{color:tokens.color.muted,fontSize:22,width:44,textAlign:'center'},input:{height:54,flex:1,color:tokens.color.text,paddingHorizontal:0,fontSize:16,outlineStyle:'none'},clear:{width:48,height:48,alignItems:'center',justifyContent:'center'},clearText:{color:tokens.color.text,fontSize:26},explore:{marginTop:28},sectionTitle:{color:tokens.color.text,fontSize:20,fontWeight:'850',marginBottom:14},chips:{flexDirection:'row',flexWrap:'wrap',gap:10},chip:{minHeight:44,paddingHorizontal:16,borderRadius:22,borderWidth:1,borderColor:tokens.color.border,justifyContent:'center'},pressed:{opacity:.6},chipText:{color:tokens.color.text,fontWeight:'700'},grid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginTop:24},skeletonGrid:{flexDirection:'row',flexWrap:'wrap',gap:12,marginTop:24},skeleton:{width:'46%',aspectRatio:2/3,borderRadius:10,backgroundColor:'#202028'}});
