import React, { useEffect, useState } from 'react';
import { ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { api } from '../services/api';
import { arrayFrom } from '../utils/content';
import { ContentCard } from '../components/ContentCard';
import { StatePanel } from '../components/StatePanel';
import { tokens } from '../theme/tokens';
export function SearchScreen({onOpen}) { const[q,setQ]=useState(''),[items,setItems]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[attempt,setAttempt]=useState(0); useEffect(()=>{if(q.trim().length<2){setItems([]);setError('');return;}const controller=new AbortController(),timer=setTimeout(async()=>{setLoading(true);setError('');try{const data=await api(`/api/search?q=${encodeURIComponent(q.trim())}`,{signal:controller.signal});setItems(arrayFrom(data,'results'))}catch(e){if(e.code!=='TIMEOUT')setError(e.message)}finally{setLoading(false)}},350);return()=>{clearTimeout(timer);controller.abort()}},[q,attempt]); return <ScrollView keyboardShouldPersistTaps="handled" style={s.page} contentContainerStyle={s.content}><Text accessibilityRole="header" style={s.title}>Search</Text><TextInput accessibilityLabel="Search Ripple" autoFocus value={q} onChangeText={setQ} placeholder="Titles, creators, genres and languages" placeholderTextColor="#777380" style={s.input}/>{loading?<StatePanel busy title="Searching" message="Searching the Ripple catalogue."/>:error?<StatePanel title="Search couldn’t load" message={error} action="Try again" onAction={()=>setAttempt(x=>x+1)}/>:q.trim().length<2?<Text style={s.hint}>Enter at least two characters. Results come directly from the Ripple catalogue.</Text>:items.length?<View style={s.grid}>{items.map(item=><ContentCard key={item.id||item._id} item={item} onOpen={onOpen}/>)}</View>:<StatePanel title="No results" message="Try a different title, creator, genre, or language."/>}</ScrollView>; }
const s=StyleSheet.create({page:{flex:1,backgroundColor:tokens.color.background},content:{padding:24,paddingBottom:90},title:{color:tokens.color.text,fontSize:36,fontWeight:'900',marginVertical:20},input:{height:54,borderWidth:1,borderColor:tokens.color.border,borderRadius:12,backgroundColor:tokens.color.surface,color:tokens.color.text,paddingHorizontal:16,fontSize:16},hint:{color:tokens.color.muted,marginTop:18},grid:{flexDirection:'row',flexWrap:'wrap',gap:16,marginTop:24}});
