import React, { useRef } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions } from 'react-native';
import { ContentCard } from './ContentCard';
import { tokens } from '../theme/tokens';
import { isTouchDevice, pageGutter } from '../utils/layout';

export function ContentRail({row,onOpen,technical=false}) {
  const rail=useRef(null), offset=useRef(0), dragged=useRef(false); const {width}=useWindowDimensions();
  if (!row?.items?.length) return null;
  const gutter=pageGutter(width), arrows=width>=1024&&!isTouchDevice();
  const move=direction=>rail.current?.scrollTo?.({x:Math.max(0,offset.current+direction*Math.max(280,width*.72)),animated:true});
  const open=item=>{if(!dragged.current)onOpen(item)};
  return <View style={[s.section,width<768&&s.mobileSection,technical&&s.technical]}><View style={[s.head,{paddingHorizontal:gutter}]}><View style={s.headingCopy}><Text accessibilityRole="header" style={s.title}>{row.title}</Text>{row.reason?<Text numberOfLines={2} style={s.reason}>{row.reason}</Text>:null}</View>{row.nextCursor?<Pressable accessibilityRole="button"><Text style={s.view}>View all</Text></Pressable>:null}</View><View style={s.railWrap}>{arrows?<Pressable accessibilityRole="button" accessibilityLabel={`Scroll ${row.title} left`} onPress={()=>move(-1)} style={[s.arrow,s.left]}><Text style={s.arrowText}>‹</Text></Pressable>:null}<ScrollView ref={rail} onScrollBeginDrag={()=>{dragged.current=true}} onMomentumScrollEnd={()=>{dragged.current=false}} onScrollEndDrag={()=>setTimeout(()=>{dragged.current=false},100)} onScroll={event=>{offset.current=event.nativeEvent.contentOffset.x}} scrollEventThrottle={32} horizontal showsHorizontalScrollIndicator={false} decelerationRate="fast" snapToAlignment="start" contentContainerStyle={[s.rail,{paddingHorizontal:gutter,gap:width<768?12:width<1024?14:16,scrollPaddingInline:gutter}]}>{row.items.map((item,index)=><ContentCard key={item.id||item._id||index} item={item} portrait={row.portrait} technical={technical} rank={row.displayRanking===true&&Number.isInteger(item.rank)?item.rank:undefined} onOpen={()=>open(item)}/>)}</ScrollView>{arrows?<Pressable accessibilityRole="button" accessibilityLabel={`Scroll ${row.title} right`} onPress={()=>move(1)} style={[s.arrow,s.right]}><Text style={s.arrowText}>›</Text></Pressable>:null}</View></View>;
}
const s=StyleSheet.create({section:{marginTop:36,zIndex:2},mobileSection:{marginTop:34},technical:{marginTop:64,opacity:.8},head:{marginBottom:16,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},headingCopy:{gap:7,minWidth:0},title:{color:tokens.color.text,fontSize:22,lineHeight:27,fontWeight:'850',letterSpacing:-.3},reason:{color:tokens.color.muted,fontSize:14,lineHeight:20},view:{color:tokens.color.accentSoft,fontWeight:'700'},railWrap:{position:'relative'},rail:{paddingBottom:8,scrollSnapType:'x proximity',overscrollBehaviorInline:'contain'},arrow:{position:'absolute',top:0,bottom:8,width:44,zIndex:10,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(5,5,9,.68)'},left:{left:0},right:{right:0},arrowText:{color:'#fff',fontSize:38,fontWeight:'300'}});
