import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Modal, Platform, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { isHlsUrl, isValidHttpsVideoUrl } from '../../playerReliability';
import { tokens } from '../theme/tokens';
let loader;
function loadHls(){ if(globalThis.Hls)return Promise.resolve(globalThis.Hls); loader||=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/hls.js@1.6.13/dist/hls.min.js';script.onload=()=>resolve(globalThis.Hls);script.onerror=()=>reject(new Error('HLS support could not be loaded.'));document.head.appendChild(script)});return loader; }
export function VideoPlayer({item,onClose,onProgress}) { const video=useRef(null),engine=useRef(null),last=useRef(0); const [status,setStatus]=useState('loading'),[error,setError]=useState(''); const url=item?.videoUrl||item?.playbackUrl||item?.url;
  const attach=useCallback(async()=>{if(Platform.OS!=='web'||!video.current||!isValidHttpsVideoUrl(url)){setError('A secure playback stream is not available.');setStatus('error');return;} setStatus('loading');setError('');try{if(isHlsUrl(url,item?.mimeType)&&!video.current.canPlayType('application/vnd.apple.mpegurl')){const Hls=await loadHls();if(!Hls?.isSupported())throw new Error('This browser cannot play this stream.');engine.current=new Hls();engine.current.loadSource(url);engine.current.attachMedia(video.current)}else video.current.src=url;video.current.load();}catch(e){setError(e.message);setStatus('error')}},[url,item?.mimeType]);
  useEffect(()=>{attach();return()=>{const v=video.current;if(v){v.pause();v.removeAttribute('src');v.load()}engine.current?.destroy()}},[attach]);
  if(!item)return null; function close(){const v=video.current;if(v?.duration)onProgress?.(v.currentTime,v.duration,'closed');onClose();}
  return <Modal visible animationType="fade" onRequestClose={close}><SafeAreaView style={s.root}><View style={s.top}><Text style={s.logo}>RIPPLE</Text><Pressable accessibilityRole="button" accessibilityLabel="Close player" onPress={close} style={s.close}><Text style={s.closeText}>Close</Text></Pressable></View><View style={s.stage}>{Platform.OS==='web'?<video ref={video} controls playsInline poster={item.posterUrl||item.thumbnailUrl} aria-label={`${item.title} video player`} onCanPlay={()=>setStatus('ready')} onPlaying={()=>setStatus('ready')} onWaiting={()=>setStatus('loading')} onPause={e=>onProgress?.(e.currentTarget.currentTime,e.currentTarget.duration,'paused')} onSeeked={e=>onProgress?.(e.currentTarget.currentTime,e.currentTarget.duration,'seeked')} onTimeUpdate={e=>{const v=e.currentTarget;if(v.currentTime-last.current>=15){last.current=v.currentTime;onProgress?.(v.currentTime,v.duration,'playing')}}} onEnded={e=>onProgress?.(e.currentTarget.duration,e.currentTarget.duration,'completed')} style={{width:'100%',maxHeight:'78vh',aspectRatio:'16 / 9',background:'#000'}}>{(item.captions||[]).map((track,i)=><track key={track.src||i} kind="subtitles" src={track.src} srcLang={track.language} label={track.label}/>)}</video>:null}{status==='loading'?<View style={s.overlay}><ActivityIndicator color={tokens.color.accentSoft}/><Text style={s.message}>Preparing secure playback…</Text></View>:null}{status==='error'?<View accessibilityRole="alert" style={s.overlay}><Text style={s.errorTitle}>Playback unavailable</Text><Text style={s.message}>{error}</Text><Pressable onPress={attach} style={s.retry}><Text style={s.retryText}>Retry</Text></Pressable></View>:null}</View><Text style={s.title}>{item.title}</Text></SafeAreaView></Modal>; }
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#05030d'},top:{height:68,paddingHorizontal:20,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},logo:{color:'#fff',fontWeight:'900',letterSpacing:4},close:{minHeight:44,paddingHorizontal:16,justifyContent:'center'},closeText:{color:'#fff',fontWeight:'800'},stage:{width:'100%',maxWidth:1200,alignSelf:'center',position:'relative',minHeight:240,justifyContent:'center',backgroundColor:'#05030d'},overlay:{...StyleSheet.absoluteFillObject,alignItems:'center',justifyContent:'center',gap:12,backgroundColor:'rgba(5,3,13,.92)'},message:{color:tokens.color.muted,textAlign:'center'},errorTitle:{color:'#fff',fontSize:22,fontWeight:'900'},retry:{minHeight:44,paddingHorizontal:20,borderRadius:8,backgroundColor:'#fff',justifyContent:'center'},retryText:{fontWeight:'800'},title:{color:'#fff',fontSize:24,fontWeight:'900',padding:24}});
