import React, { useCallback, useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Modal, Platform, Pressable, SafeAreaView, StyleSheet, Text, View } from 'react-native';
import { isHlsUrl, isValidHttpsVideoUrl } from '../../playerReliability';
import { tokens } from '../theme/tokens';
import { isTV, useTVRemote } from '../tv/useTVRemote';
let loader;
function loadHls(){if(globalThis.Hls)return Promise.resolve(globalThis.Hls);loader||=new Promise((resolve,reject)=>{const script=document.createElement('script');script.src='https://cdn.jsdelivr.net/npm/hls.js@1.6.13/dist/hls.min.js';script.onload=()=>resolve(globalThis.Hls);script.onerror=()=>reject(new Error('HLS support could not be loaded.'));document.head.appendChild(script)});return loader}
export function VideoPlayer({item,onClose,onProgress}) {
  const video=useRef(null),engine=useRef(null),last=useRef(0);const[status,setStatus]=useState('loading'),[error,setError]=useState(''),[paused,setPaused]=useState(false);const url=item?.videoUrl||item?.playbackUrl||item?.url;
  const attach=useCallback(async()=>{if(Platform.OS!=='web'||!video.current||!isValidHttpsVideoUrl(url)){if(!isTV){setError('A secure playback stream is not available.');setStatus('error')}return}setStatus('loading');setError('');try{if(isHlsUrl(url,item?.mimeType)&&!video.current.canPlayType('application/vnd.apple.mpegurl')){const Hls=await loadHls();if(!Hls?.isSupported())throw new Error('This browser cannot play this stream.');engine.current=new Hls();engine.current.loadSource(url);engine.current.attachMedia(video.current)}else{video.current.src=url;video.current.load()}}catch(e){setError(e.message);setStatus('error')}},[url,item?.mimeType]);
  const toggle=useCallback(()=>{const v=video.current;if(v){v.paused?v.play():v.pause();setPaused(!v.paused)}},[]);
  const seek=useCallback(delta=>{const v=video.current;if(v&&Number.isFinite(v.duration))v.currentTime=Math.max(0,Math.min(v.duration,v.currentTime+delta))},[]);
  const close=useCallback(()=>{const v=video.current;if(v?.duration)onProgress?.(v.currentTime,v.duration,'closed');onClose()},[onClose,onProgress]);
  const remote=useCallback(event=>{if(event?.eventType==='playPause'||event?.eventType==='select')toggle();else if(event?.eventType==='left')seek(-10);else if(event?.eventType==='right')seek(10)},[seek,toggle]);
  useTVRemote(remote,item?close:undefined);
  useEffect(()=>{attach();return()=>{const v=video.current;if(v){v.pause();v.removeAttribute?.('src');v.load?.()}engine.current?.destroy()}},[attach]);
  if(!item)return null;
  const button=(label,action,preferred=false)=><Pressable hasTVPreferredFocus={preferred} onPress={action} style={({focused})=>[s.control,focused&&s.focus]}><Text style={s.controlText}>{label}</Text></Pressable>;
  return <Modal visible animationType="fade" onRequestClose={close}><SafeAreaView style={s.root}><View style={s.top}><Text style={s.logo}>RIPPLE</Text>{button('Close',close,isTV)}</View><View style={s.stage}>{Platform.OS==='web'?<video ref={video} controls playsInline poster={item.posterUrl||item.thumbnailUrl} aria-label={`${item.title} video player`} onCanPlay={()=>setStatus('ready')} onPlaying={()=>{setPaused(false);setStatus('ready')}} onWaiting={()=>setStatus('loading')} onPause={e=>{setPaused(true);onProgress?.(e.currentTarget.currentTime,e.currentTarget.duration,'paused')}} onTimeUpdate={e=>{const v=e.currentTarget;if(v.currentTime-last.current>=15){last.current=v.currentTime;onProgress?.(v.currentTime,v.duration,'playing')}}} style={{width:'100%',maxHeight:'78vh',aspectRatio:'16 / 9',background:'#000'}}/>:<View style={s.nativeNotice}><Text style={s.errorTitle}>TV playback controls ready</Text><Text style={s.message}>Select plays or pauses. Left and Right seek 10 seconds. Back closes the player.</Text></View>}{status==='loading'&&Platform.OS==='web'?<View style={s.overlay}><ActivityIndicator color={tokens.color.accentSoft}/><Text style={s.message}>Preparing secure playback…</Text></View>:null}{status==='error'?<View accessibilityRole="alert" style={s.overlay}><Text style={s.errorTitle}>Playback unavailable</Text><Text style={s.message}>{error}</Text>{button('Retry',attach)}</View>:null}</View>{isTV?<View style={s.controls}>{button('−10s',()=>seek(-10))}{button(paused?'Play':'Pause',toggle)}{button('+10s',()=>seek(10))}</View>:null}<Text style={s.title}>{item.title}</Text></SafeAreaView></Modal>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#05030d'},top:{height:76,paddingHorizontal:28,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},logo:{color:'#fff',fontWeight:'900',letterSpacing:4},stage:{width:'100%',maxWidth:1200,alignSelf:'center',position:'relative',minHeight:300,justifyContent:'center',backgroundColor:'#000'},nativeNotice:{alignItems:'center',gap:14,padding:48},overlay:{...StyleSheet.absoluteFillObject,alignItems:'center',justifyContent:'center',gap:12,backgroundColor:'rgba(5,3,13,.92)'},message:{color:tokens.color.muted,textAlign:'center',fontSize:18},errorTitle:{color:'#fff',fontSize:24,fontWeight:'900'},controls:{flexDirection:'row',justifyContent:'center',gap:24,marginTop:24},control:{minHeight:52,minWidth:110,paddingHorizontal:20,borderRadius:8,borderWidth:2,borderColor:'rgba(255,255,255,.2)',alignItems:'center',justifyContent:'center'},focus:{backgroundColor:tokens.color.accent,borderColor:'#fff',transform:[{scale:1.08}]},controlText:{color:'#fff',fontWeight:'900',fontSize:17},title:{color:'#fff',fontSize:24,fontWeight:'900',padding:24}});
